server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vehicle_management
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: vehicle-management-service
  sql:
    init:
      mode: always
