spring:
  application:
    name: payment-service
  config:
    import: optional:configserver:http://localhost:8888

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop