spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: user-service   # still needed for resolving user-service.yml
  cloud:
    config:
      failFast: true
